server:
  port: 8082
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  application:
    name: zhiyou
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiyou
    username: root
    password: root
  session:
    #单位是分钟
    timeout: 86400
    store-type: redis
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      #        设置文件上传大小限制
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 100MB
      max-request-size: 150MB
  redis:
    host: 172.20.1.134
    port: 6379
    password: 123321
    database: 1
  jackson:
#    date-format: yyyy年MM月dd日 HH:mm:ss
    timeZone: Asia/Shanghai
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

